name: Build Docs
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Sphinx/Doxygen
        run: |
          sudo apt update
          sudo apt install -y python3-pip
      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          pip install myst-parser
          pip install ghp-import # only required by this yaml for publishing the docs
      - name: Build Website
        working-directory: ./docs/
        run: |
          make html
      - name: Run ghp-import
        run: |
          ghp-import -n -p -f docs/build/html
